### ISSUE TITLE
It would be useful to have a TestRule version of GuiceBerryRule

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zorzella/guiceberry#25]
```
MethodRule is semi-deprecated (it was deprecated, but I think more recently has 
been un-deprecated) and it doesn't work with certain new JUnit4 features such 
as RuleChain. Unfortunately, we can't make a non-breaking change to update 
GuiceBerryRule to TestRule as the target object is not passed into the apply 
method for TestRule. Attached is a proposed implementation of 
GuiceBerryTestRule (and if added, we should also probably deprecate 
GuiceBerryRule).


```

Original issue reported on code.google.com by `fishe...@google.com` on 29 Mar 2013 at 4:52

Attachments:
- [GuiceBerryTestRule.java](https://storage.googleapis.com/google-code-attachments/guiceberry/issue-25/comment-0/GuiceBerryTestRule.java)

**Comment by zorzella** [comment]
FYI, I'm still waiting for someone to finish to polish the patch that was sent, and I'll happily apply it. Here are the invariants:

1. I'm keeping  GuiceBerryRule around. Even if I wanted to kill it, I couldn't, and, unless you need a TestRule, using GBR is a safer and more compact.

2. I'm happy to name the new rule GuiceBerryTestRule

Essentially I just need a patch with the "throws" issue resolved, javadoc and tests.

**Comment by kcooney** [comment]
@zorzella where can I find the patch you are referring to? What is the "throws issue"?

**Comment by zorzella** [comment]
Hey, Kevin.

the "patch" is the attachment in the first comment (i.e. the bug report itself) -- this predates the conversion to GitHub, so it's not like it's a branch or something.

The "throws issue" is what I think you yourself described: "Note that the supplied patch should be modified to cause evalulate() to throw an exception if description.isSuite() returns true (because GuiceBerry cannot be used as a class rule)"

I strongly encourage you to re-read my post that starts with "Let me see if I get this straight:", as my proposal for the "polish" I talk about is described there.

Peace,

Z

**Comment by zorzella** [comment]
Closing old/obsolete issues.
